import { NextRequest, NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

/**
 * GET — Returns the Supabase Google OAuth URL for the Chrome extension.
 * The extension calls this before launching chrome.identity.launchWebAuthFlow.
 *
 * Query params:
 *   redirect – the extension's redirect URL (https://<ext-id>.chromiumapp.org/)
 *   code_challenge – PKCE code challenge generated by the extension
 */
export async function GET(req: NextRequest) {
  const redirect = req.nextUrl.searchParams.get('redirect');
  const codeChallenge = req.nextUrl.searchParams.get('code_challenge');

  if (!redirect || !codeChallenge) {
    return NextResponse.json({ error: 'Missing redirect or code_challenge' }, { status: 400 });
  }

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  if (!supabaseUrl) {
    return NextResponse.json({ error: 'Server configuration error' }, { status: 500 });
  }

  const authUrl = new URL(`${supabaseUrl}/auth/v1/authorize`);
  authUrl.searchParams.set('provider', 'google');
  authUrl.searchParams.set('redirect_to', redirect);
  authUrl.searchParams.set('code_challenge', codeChallenge);
  authUrl.searchParams.set('code_challenge_method', 'S256');

  return NextResponse.json({ url: authUrl.toString() });
}

/**
 * POST — Exchanges the authorization code + PKCE verifier for session tokens.
 * Called by the extension after launchWebAuthFlow returns a code.
 *
 * Body: { code, codeVerifier }
 */
export async function POST(req: NextRequest) {
  const { code, codeVerifier } = await req.json().catch(() => ({}));
  if (!code || !codeVerifier) {
    return NextResponse.json({ error: 'Missing code or codeVerifier' }, { status: 400 });
  }

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  if (!supabaseUrl || !supabaseKey) {
    return NextResponse.json({ error: 'Server configuration error' }, { status: 500 });
  }

  const tokenRes = await fetch(`${supabaseUrl}/auth/v1/token?grant_type=pkce`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'apikey': supabaseKey,
    },
    body: JSON.stringify({
      auth_code: code,
      code_verifier: codeVerifier,
    }),
  });

  if (!tokenRes.ok) {
    const err = await tokenRes.json().catch(() => ({}));
    return NextResponse.json(
      { error: err.error_description || err.msg || 'Google sign-in failed' },
      { status: 401 },
    );
  }

  const data = await tokenRes.json();
  return NextResponse.json({
    token: data.access_token,
    refreshToken: data.refresh_token,
    expiresAt: data.expires_at,
  });
}
