import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service — KChime',
  description: 'Terms of service for KChime, the AI reply assistant.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="mx-auto max-w-2xl px-6 py-16 md:py-24">
        <Link href="/" className="text-sm text-teal-600 hover:underline font-medium">
          &larr; Back to KChime
        </Link>

        <h1 className="mt-6 text-3xl font-extrabold text-gray-900">Terms of Service</h1>
        <p className="mt-2 text-sm text-gray-400">Last updated: March 2026</p>

        <div className="mt-10 space-y-8 text-gray-600 text-sm leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">Acceptance of terms</h2>
            <p>
              By using KChime, you agree to these terms of service. If you do not agree, please do not use the app.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">Description of service</h2>
            <p>
              KChime is an AI-powered reply assistant that suggests responses for texts, emails, and chats. The service is provided &ldquo;as is&rdquo; and suggestions are generated by AI models.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">User responsibilities</h2>
            <p>
              You are responsible for the messages you send using KChime suggestions. AI-generated replies are suggestions only — always review before sending.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">Subscriptions and billing</h2>
            <p>
              KChime offers a free tier and a paid Pro plan. Pro subscriptions are billed monthly or annually through Stripe. You can cancel anytime from your account settings.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">Limitation of liability</h2>
            <p>
              KChime is not liable for any consequences arising from the use of AI-generated reply suggestions. Use your own judgment when sending messages.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">Contact</h2>
            <p>
              For questions about these terms, contact us at{' '}
              <a href="mailto:support@kchime.app" className="text-teal-600 hover:underline">
                support@kchime.app
              </a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
