import type { Scenario, ScenarioCategory } from '@/types';

export const scenarios: Scenario[] = [
  { id: 'st-1', title: 'Crazy weather', category: 'Small Talk', openingLine: "Can you believe this weather? It's like summer in the middle of winter!", context: 'Someone at work or in a coffee shop comments on the unusual weather.', suggestedReplies: ["Right? I had to dig my shorts out of storage!", "I know, I keep forgetting what season it is.", "Yeah, the weather's been all over the place lately.", "I'll take it! Beats freezing, honestly."] },
  { id: 'st-2', title: 'TGIF', category: 'Small Talk', openingLine: 'TGIF, am I right?', context: 'A coworker passes you in the hallway on a Friday afternoon.', suggestedReplies: ['Oh man, you have no idea. This week dragged.', "Tell me about it — counting down the minutes!", 'Yes! I have big plans of doing absolutely nothing.', 'Same! Happy Friday to you.'] },
  { id: 'st-3', title: 'Year going fast', category: 'Small Talk', openingLine: "Can you believe it's already November? Where did this year go?", context: 'Casual conversation, maybe while waiting for a meeting to start.', suggestedReplies: ["I know, it's like the year just flew by!", "Seriously! I still feel like it's spring.", 'Time really flies — especially the good parts.', "Yeah, the holidays will be here before we know it."] },
  { id: 'st-4', title: 'Need coffee', category: 'Small Talk', openingLine: 'You look like you could use a coffee. Rough morning?', context: 'A friendly coworker or acquaintance notices you seem tired.', suggestedReplies: ["Is it that obvious? Yeah, it was a rough one.", "Ha, you're not wrong — I'm running on fumes today.", "Actually, I'm on my second cup and still not quite there.", "I'm okay, just didn't sleep great. Thanks for asking!"] },
  { id: 'st-5', title: 'Nice haircut', category: 'Small Talk', openingLine: 'Hey, did you get a haircut? Looks great!', context: 'Someone at work or a friend notices your new haircut.', suggestedReplies: ['Yeah, just got it done yesterday! Thanks!', 'Ha, finally right? Way overdue.', "Thank you! I was nervous about going shorter.", "Oh, thanks for noticing! I wasn't sure about it."] },
  { id: 'st-6', title: 'Traffic was bad', category: 'Small Talk', openingLine: 'Traffic was brutal today. Took me forever to get here.', context: 'Someone venting about their commute after arriving somewhere.', suggestedReplies: ["Ugh, same. I don't know what was going on out there.", 'Yeah, I heard there was an accident on the highway.', "That's the worst. I ended up taking the back roads.", "Tell me about it — I left early and still barely made it."] },
  { id: 'st-7', title: 'Grocery prices', category: 'Small Talk', openingLine: "Have you seen how expensive groceries are getting? It's unreal.", context: 'Someone expressing frustration about rising food costs.', suggestedReplies: ['I know! I almost put things back at the checkout.', "Right? My bill has basically doubled in the last year.", "Seriously. I've started meal prepping just to save money.", "Yeah, I've been going to different stores to find better prices."] },
  { id: 'wp-1', title: 'Weekend plans', category: 'Weekend Plans', openingLine: 'Got any fun plans for the weekend?', context: 'Asked by a coworker or friend on a Thursday or Friday.', suggestedReplies: ['Nothing major — just trying to relax and recharge.', "Yeah! We're checking out that new restaurant downtown.", 'Might go hiking if the weather holds up. You?', 'Honestly just looking forward to sleeping in, haha.'] },
  { id: 'wp-2', title: 'How was your weekend', category: 'Weekend Plans', openingLine: 'How was your weekend? Do anything fun?', context: 'A Monday morning greeting from a coworker or classmate.', suggestedReplies: ["It was nice — low-key, just what I needed.", "Pretty good! We went to the farmer's market.", 'Honestly, I mostly just relaxed. Felt great.', "It went by too fast, but I can't complain!"] },
  { id: 'wp-3', title: 'Long weekend', category: 'Weekend Plans', openingLine: 'Big plans for the long weekend?', context: 'Before a holiday weekend like Memorial Day or Labor Day.', suggestedReplies: ['Thinking about a little road trip — nothing too crazy.', 'Just a barbecue with some friends. Should be fun!', 'No big plans, just enjoying the extra day off.', "Haven't decided yet — might just wing it. You?"] },
  { id: 'wp-4', title: 'Any good shows?', category: 'Weekend Plans', openingLine: 'I need something new to watch this weekend. Got any recommendations?', context: 'A friend or coworker looking for a TV or movie suggestion.', suggestedReplies: ["Oh, have you seen Severance? It's so good.", "Depends — are you into dramas, or more comedy?", "I just started this new series and I'm already hooked.", "Honestly, I've been rewatching old stuff. Not super helpful, haha."] },
  { id: 'wp-5', title: 'Birthday plans', category: 'Weekend Plans', openingLine: "It's my birthday this weekend! We're going out Saturday — you should come!", context: 'A friend or coworker inviting you to their birthday celebration.', suggestedReplies: ["Happy early birthday! I'd love to come — what time?", 'Oh nice, happy birthday! Send me the details!', "That sounds fun! Where are you guys going?", "Congrats! I'll try to make it — what's the plan?"] },
  { id: 'wb-1', title: 'Ugh Mondays', category: 'Workplace Banter', openingLine: "Ugh, Mondays. Why can't we have four-day work weeks?", context: 'A coworker venting a bit at the start of the week.', suggestedReplies: ["Right? I would be so much more productive with Fridays off.", "Ha, I'd vote for that in a heartbeat.", 'Tell me about it. Coffee is the only thing keeping me going.', "Agreed. Though at least it's a fresh start, I guess?"] },
  { id: 'wb-2', title: 'That email', category: 'Workplace Banter', openingLine: 'Did you see that email from the boss this morning?', context: 'A coworker asking about a recent company-wide email.', suggestedReplies: ['Yeah, I read it. Definitely a lot to process.', "I glanced at it — what did you think?", "I haven't had a chance yet. Was it important?", 'Oh yeah. Sounds like some changes are coming.'] },
  { id: 'wb-3', title: 'Project update', category: 'Workplace Banter', openingLine: 'Hey, how\'s that project coming along?', context: 'A colleague asking for an informal progress update.', suggestedReplies: ['Pretty good! Almost at the finish line.', "Moving along — a few bumps, but nothing we can't handle.", "It's coming together. Should have an update by end of week.", "Slowly but surely! It's been a busy week."] },
  { id: 'wb-4', title: "You're here early", category: 'Workplace Banter', openingLine: "Whoa, you're here early! Trying to impress someone?", context: 'A coworker teasing you for arriving before everyone else.', suggestedReplies: ['Ha, just trying to get ahead before the chaos starts.', "Early bird gets the quiet office — it's honestly amazing.", "Don't tell anyone. I need the parking spot.", "Don't be fooled — I just couldn't sleep. Ha."] },
  { id: 'wb-5', title: 'Lunch plans', category: 'Workplace Banter', openingLine: "Hey, you got lunch plans? We're heading to that Thai place.", context: 'A coworker inviting you to join the lunch group.', suggestedReplies: ["I'm in! Give me five minutes.", 'Oh, I already brought lunch today. Next time for sure!', "That place is so good. Yeah, count me in.", "I've been wanting to try that — absolutely."] },
  { id: 'wb-6', title: 'Tech issues', category: 'Workplace Banter', openingLine: 'The printer is down again. Why is it always the printer?', context: 'A coworker frustrated with office technology problems.', suggestedReplies: ["Ha, it's like a law of the universe at this point.", "I just email everything to myself. Gave up on printing.", 'Did you try turning it off and on again? Classic fix.', "I swear that thing is older than the company. So frustrating."] },
  { id: 'sp-1', title: 'The game last night', category: 'Sports Talk', openingLine: 'Did you catch the game last night? What a finish!', context: 'A sports fan excited about a big game — could be any major sport.', suggestedReplies: ["Yes! I couldn't believe that ending — my heart was pounding.", 'I caught the highlights — wild game!', 'I missed it, but I heard it was crazy. Who won?', "Oh man, I had to turn it off — too stressful! Ha."] },
  { id: 'sp-2', title: 'Playoffs talk', category: 'Sports Talk', openingLine: "Can you believe what happened in the playoffs? That was insane.", context: 'Someone reacting to a surprise playoff result.', suggestedReplies: ["I know — totally didn't see that coming!", "Right? I had to rewatch it just to believe it.", "I heard about it! Sports can be so unpredictable.", "Yeah, I'd say that's an upset of the year candidate."] },
  { id: 'sp-3', title: 'Super Bowl', category: 'Sports Talk', openingLine: 'You watching the Super Bowl this year?', context: 'Common question in January or early February.', suggestedReplies: ["For sure — I'm in it for the halftime show and the snacks.", "Of course! Got a little get-together planned.", "Probably! I'm not the biggest fan but it's always fun to watch.", "Definitely. I don't have a strong team, but I love the vibe."] },
  { id: 'sp-4', title: 'Fantasy sports', category: 'Sports Talk', openingLine: "Ugh, my fantasy team tanked this week. You doing fantasy?", context: 'A friend or coworker complaining about their fantasy sports team.', suggestedReplies: ["Ha, I feel that. Mine hasn't been great either.", "Yeah, I'm in a league — it's been a rollercoaster!", "I don't do fantasy, but it sounds intense!", 'Oh no. Did someone get injured on your team?'] },
  { id: 'sp-5', title: 'Big trade', category: 'Sports Talk', openingLine: "Did you hear about that trade? I can't believe they let him go.", context: 'A sports fan reacting to a major player trade or signing.', suggestedReplies: ["I know! That one shocked me — didn't see it coming at all.", "Yeah, that's a big move. Gonna shake things up for sure.", "I saw the headline but haven't caught up on the details. What happened?", "Honestly, I think it could work out. We'll see."] },
  { id: 'sp-6', title: 'Your team stinks', category: 'Sports Talk', openingLine: "Ha, your team is really struggling this season, huh?", context: "A friend or coworker ribbing you about your team's poor performance.", suggestedReplies: ["Yeah yeah, I know. Don't rub it in.", "It's been rough. I'm still a fan though — for better or worse.", "Ha, at least we're consistent… consistently bad.", "I'm choosing to believe in a second-half comeback. Don't take that from me."] },
  { id: 'ah-1', title: 'Seafood diet joke', category: 'American Humor', openingLine: "I'm on a seafood diet. I see food, I eat it.", context: 'Someone cracking a classic dad joke, usually around food.', suggestedReplies: ["Ha! I think I'm on the same diet.", "Classic. I've been on that diet my whole life.", "Oh no, a dad joke. I love it though.", "Ha! That one never gets old."] },
  { id: 'ah-2', title: 'Boss said good day', category: 'American Humor', openingLine: 'My boss told me to have a good day, so I went home.', context: 'Someone telling a light joke about work-life balance.', suggestedReplies: ["Ha! That's called following instructions.", 'Honestly, sounds like solid logic to me.', "Did it work? That's the dream.", "Ha, that might be the most efficient workday ever."] },
  { id: 'ah-3', title: 'I told my wife', category: 'American Humor', openingLine: 'I told my wife she should embrace her mistakes. She gave me a hug.', context: 'Classic dad joke punchline from a coworker or friend.', suggestedReplies: ["Ha! That's a good one.", "Oh wow, did not see that coming. Nicely done.", 'Haha, she had the perfect response.', "That's sweet in a punny kind of way."] },
  { id: 'ah-4', title: 'Parallel parking', category: 'American Humor', openingLine: 'I finally parallel parked on my first try. Best day of my life.', context: 'Someone sharing a small but relatable victory with exaggerated pride.', suggestedReplies: ['Ha! That deserves a trophy honestly.', "Okay but that's genuinely impressive. I never get it first try.", 'That feeling is unmatched. Savor it.', "I would have circled the block and found a different spot. You're braver than me."] },
  { id: 'ah-5', title: '5 more minutes', category: 'American Humor', openingLine: 'I set three alarms this morning and still hit snooze on all of them.', context: 'Someone sharing a relatable morning struggle in a self-deprecating way.', suggestedReplies: ["Ha, same honestly. My alarm is basically decoration at this point.", "Three alarms is my minimum. It's a whole system.", 'I respect the commitment to sleep. Truly.', "Honestly impressive. Most people give up after two."] },
  { id: 'hg-1', title: 'Happy holidays', category: 'Holiday Greetings', openingLine: 'Happy holidays! Got any fun plans?', context: 'Someone greeting you during the holiday season (late November–January).', suggestedReplies: ['Happy holidays! Yeah, heading home to see family.', "Thanks! Same to you — we're keeping it low-key this year.", "Happy holidays! Just relaxing and enjoying the time off.", "Thank you! It's gonna be a good one, I think."] },
  { id: 'hg-2', title: 'Thanksgiving plans', category: 'Holiday Greetings', openingLine: 'What are you doing for Thanksgiving?', context: 'Asked by a coworker or friend in November.', suggestedReplies: ["Heading to my in-laws — it's always a full house!", 'Just a small dinner with close friends this year.', 'Doing a Friendsgiving actually — should be fun!', 'Nothing too big — cooking at home and keeping it relaxed.'] },
  { id: 'hg-3', title: 'Christmas shopping', category: 'Holiday Greetings', openingLine: 'Is it too early to start talking about Christmas shopping?', context: 'Someone mentioning holiday shopping stress, often in October or November.', suggestedReplies: ['Nope! I already started. Black Friday waits for no one.', "Ha, I haven't even thought about it. I should probably start.", 'Never too early — the earlier the better to avoid the chaos.', "Ugh, I keep putting it off. Remind me to get on that!"] },
  { id: 'hg-4', title: 'Happy New Year', category: 'Holiday Greetings', openingLine: 'Happy New Year! Any resolutions this year?', context: "Someone greeting you in early January and asking about New Year's goals.", suggestedReplies: ["Happy New Year! I'm keeping it simple — just trying to be consistent.", "Thanks, same to you! Not really a resolutions person, but I've got some goals.", "Happy New Year! My resolution is to actually stick to my resolution. Ha.", 'Yes! Gym, sleep, less phone. Classic lineup.'] },
  { id: 'hg-5', title: 'Happy 4th of July', category: 'Holiday Greetings', openingLine: 'Happy Fourth! You doing anything for the holiday?', context: 'Someone wishing you a happy Independence Day and asking about plans.', suggestedReplies: ["Happy Fourth! Yeah, we're doing a barbecue with friends.", "Thanks! Just watching fireworks and relaxing. You?", "Happy Fourth! Nothing big — keeping it low-key.", "Same to you! We're heading to the park later for the fireworks."] },
  { id: 'fd-1', title: 'Where to grab lunch', category: 'Food & Dining', openingLine: "We're all going to grab lunch — any idea where you wanna go?", context: 'Coworkers or friends deciding on a lunch spot together.', suggestedReplies: ["I'm easy — whatever the group wants is fine with me.", "Ooh, how about that burger place on Main? I've been craving it.", "I'm feeling something light today — maybe a salad place?", "Surprise me! I'm not picky."] },
  { id: 'fd-2', title: 'Have you tried this place', category: 'Food & Dining', openingLine: "Have you tried that new ramen spot that just opened? It's so good.", context: 'Someone enthusiastically recommending a new restaurant.', suggestedReplies: ["Not yet! I've heard great things — we should go sometime.", 'Yes! I went last week. The broth is incredible.', "I haven't, but I love ramen. Add it to the list.", "Oh no, now I really want ramen. Thanks a lot. Ha."] },
  { id: 'fd-3', title: "Can't decide what to order", category: 'Food & Dining', openingLine: "I can never decide what to get here. It all looks so good.", context: "You're at a restaurant together and your companion is indecisive.", suggestedReplies: ['Ha, same every time. I usually just go with what I got before.', 'Just close your eyes and point. No regrets.', "What are you feeling — something heavy or light?", "Get two things and share — that's how I always handle it."] },
  { id: 'fd-4', title: 'This is so good', category: 'Food & Dining', openingLine: 'Oh my gosh, this is amazing. You have to try a bite.', context: 'Your dining companion is excited about their food and wants you to taste it.', suggestedReplies: ['Oh wow, that is really good. I should have ordered that.', 'Ha, now I have food envy. That looks incredible.', "Yes! So glad you like it. This place never disappoints.", "Mmm, thanks! Okay maybe I'll get that next time."] },
  { id: 'fd-5', title: 'Splitting the check', category: 'Food & Dining', openingLine: 'Should we just split it evenly or do you wanna do separate checks?', context: 'At the end of a meal, figuring out how to pay.', suggestedReplies: ["Split evenly is fine with me — easier.", "I'm okay either way. Whatever's easier for everyone.", "Actually, I just want to grab separate — I only had the salad.", "Split it — I'll get the tip."] },
  { id: 'fd-6', title: 'Dietary restrictions', category: 'Food & Dining', openingLine: 'Do you have any food allergies or anything I should know before I order for you?', context: "Someone is offering to order for you or planning a meal, and they're being considerate.", suggestedReplies: ["I'm good with everything — no restrictions. Thanks for asking!", "No allergies, but I'm not a big fan of spicy food.", "I'm vegetarian, so just nothing with meat. Otherwise I'm easy.", "Really appreciate you asking — just no shellfish for me."] },
  { id: 'se-1', title: 'Great party', category: 'Social Events', openingLine: "Great party, right? I'm so glad I came out tonight.", context: 'Someone you just met or know casually at a party or social event.', suggestedReplies: ["Yeah, it's a really good vibe. Glad I came too.", "For sure! I didn't expect it to be this fun.", 'It\'s great! Do you come to these often?', "Right? The host always throws a good one."] },
  { id: 'se-2', title: 'Can I get you a drink', category: 'Social Events', openingLine: "Hey, can I grab you a drink? I'm heading to the bar.", context: 'Someone offering to get you a drink at a party, bar, or event.', suggestedReplies: ["Oh, that's so nice — I'd love a water actually. Thank you!", "Sure! I'll take whatever they have on tap.", "I'm good for now, but thank you so much!", "Yes please! Anything with lemon. I appreciate it."] },
  { id: 'se-3', title: 'How do you know the host', category: 'Social Events', openingLine: 'So how do you know Jake? Are you guys old friends?', context: 'Making small talk with someone you just met at a party.', suggestedReplies: ["We went to college together — known him forever.", 'We actually work together. How about you?', 'I know him through mutual friends. You?', 'We met through a friend about a year ago. He\'s great.'] },
  { id: 'se-4', title: 'Leaving the party', category: 'Social Events', openingLine: "Hey, we're heading out — it was so good to see you! Let's catch up soon.", context: 'Someone saying goodbye at the end of a social gathering.', suggestedReplies: ["So good to see you too! Yes, let's definitely plan something.", "Already? Don't go! But yes — let's catch up for real soon.", "Drive safe! And yes, we need to hang out more.", "It was great seeing you! Text me — we'll figure something out."] },
  { id: 'se-5', title: 'Nice to meet you', category: 'Social Events', openingLine: "I'm Sarah, by the way. Nice to meet you!", context: 'Someone introduces themselves to you at a party or networking event.', suggestedReplies: ["Nice to meet you too, Sarah! I'm [name]. Are you from around here?", "Hey Sarah! Great to meet you. How do you know everyone here?", "Sarah, nice to meet you! I'm [name]. First time at one of these?", "Hey! Nice to meet you. I'm [name] — glad someone introduced themselves!"] },
  { id: 'cp-1', title: 'Love your outfit', category: 'Compliments', openingLine: 'I love your outfit today! Where did you get that jacket?', context: 'A coworker, friend, or acquaintance complimenting what you\'re wearing.', suggestedReplies: ["Thank you! It's from Zara — found it on sale.", "Aw, thanks! I got it online — I can send you the link if you want.", 'Oh thanks! Honestly I just threw this together this morning.', "Thank you so much! It's one of my favorites."] },
  { id: 'cp-2', title: 'Great job on that', category: 'Compliments', openingLine: 'Hey, great job on that presentation. You really nailed it.', context: 'A coworker or manager complimenting your work after a presentation or project.', suggestedReplies: ["Thank you so much! That means a lot — I put a lot into it.", "Really appreciate that! I was a little nervous, so that's a relief.", "Thanks! The team helped a lot — it was a group effort.", "Oh, thanks! I'm glad it came across well."] },
  { id: 'cp-3', title: "You're so good at this", category: 'Compliments', openingLine: "You make this look so easy. I don't know how you do it.", context: 'Someone expressing admiration for a skill you have.', suggestedReplies: ["Ha, I promise it wasn't always this way. Lots of practice.", "Thanks! Honestly I still mess up all the time — you just don't see that part.", "That's really kind of you to say. I've just been doing it a while.", "Aw, thank you! You'd pick it up fast — it just takes a bit."] },
  { id: 'cp-4', title: 'You look great', category: 'Compliments', openingLine: "Wow, you look great! Have you been working out or something?", context: 'A friend or acquaintance noticing a positive change in your appearance.', suggestedReplies: ["Ha, thanks! I've been trying to get to the gym more consistently.", "Oh, you're sweet. I've just been trying to get more sleep.", "Thank you! I've been eating better lately. Nice to hear it's showing.", "Ha, thanks for noticing! I wasn't sure if it was making a difference."] },
  { id: 'cp-5', title: 'Receiving thanks', category: 'Compliments', openingLine: "Thank you so much — I really couldn't have done it without your help.", context: 'Someone genuinely thanking you for help you gave them.', suggestedReplies: ['Of course! Happy to help anytime.', "Aw, it was nothing. Seriously, glad it worked out.", "That's so kind of you to say — it was really a team effort.", "Anytime! That's what we're here for."] },
];

export const categoryMeta: Record<ScenarioCategory, { color: string }> = {
  'Small Talk':        { color: 'bg-blue-100 text-blue-700' },
  'Weekend Plans':     { color: 'bg-orange-100 text-orange-700' },
  'Workplace Banter':  { color: 'bg-purple-100 text-purple-700' },
  'Sports Talk':       { color: 'bg-green-100 text-green-700' },
  'American Humor':    { color: 'bg-yellow-100 text-yellow-700' },
  'Holiday Greetings': { color: 'bg-red-100 text-red-700' },
  'Food & Dining':     { color: 'bg-amber-100 text-amber-700' },
  'Social Events':     { color: 'bg-pink-100 text-pink-700' },
  'Compliments':       { color: 'bg-indigo-100 text-indigo-700' },
};

export const allCategories: ScenarioCategory[] = Object.keys(categoryMeta) as ScenarioCategory[];

export function getScenariosByCategory(category: ScenarioCategory): Scenario[] {
  return scenarios.filter((s) => s.category === category);
}

export function getScenarioById(id: string): Scenario | undefined {
  return scenarios.find((s) => s.id === id);
}

export function getDailyPicks(): Scenario[] {
  const today = new Date();
  const seed = today.getFullYear() * 10000 + (today.getMonth() + 1) * 100 + today.getDate();
  const shuffled = [...scenarios].sort((a, b) => {
    const ha = hashCode(a.id + seed);
    const hb = hashCode(b.id + seed);
    return ha - hb;
  });
  return shuffled.slice(0, 3);
}

function hashCode(str: string | number): number {
  const s = String(str);
  let hash = 0;
  for (let i = 0; i < s.length; i++) {
    hash = ((hash << 5) - hash) + s.charCodeAt(i);
    hash |= 0;
  }
  return hash;
}
